local a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z=workspace,game.Players,game.Players.LocalPlayer,game:GetService("ReplicatedStorage"),game:GetService("UserInputService"),nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil,nil
local A={"ChartreusePeriastron","IvoryPeriastron","SpectralSword","CrimsonPeriastron","SpecOmegaBiograftEnergySword","DualSpecGammaBiograftEnergySword","RainbowPeriastron","Illumina","DaggerOfShatteredDimensions","SpecZetaBiograftEnergySword","SpecGammaBiograftEnergySword","Magician'sCloak","Ice Dragon Slaying Sword","FireSword","CrescendoTheSoulStealer","FangOfTsuchigumo"}
local function B(a)local b=c.Character.HumanoidRootPart local d=c.Character.HumanoidRootPart.CFrame for e=1,3 do c.Character.HumanoidRootPart.CFrame=b.CFrame*CFrame.new(0,0,1.1) task.wait() end task.wait(0.7) c.Character.HumanoidRootPart.CFrame=d end
local function C()for a,b in pairs(c.Backpack:GetChildren())do for d,e in pairs(A)do if b.Name==e then b.Parent=c.Character end end end end
local D=loadstring(game:HttpGet("https://sirius.menu/rayfield"))()
local E=D:CreateWindow({Name="🟣 Xiki | Lucky Block BG",LoadingTitle="Xiki UI",LoadingSubtitle="Modern & Clean Design",ConfigurationSaving={Enabled=true,FolderName="Xiki UI",FileName="LuckyBlock"},Discord={Enabled=false},KeySystem=false})
local F=E:CreateTab("Character",4483362458)
local G=E:CreateTab("Lucky Blocks",4483362458)
local H=E:CreateTab("Clock Time",4483362458)
local I=E:CreateTab("Advanced",4483362458)
F:CreateSection("Movement")
F:CreateSlider({Name="Walk Speed",Range={0,100},Increment=1,CurrentValue=16,Tooltip="Изменяет скорость передвижения",Callback=function(a) c.Character.Humanoid.WalkSpeed=a end})
F:CreateButton({Name="Reset Walk Speed",Callback=function() c.Character.Humanoid.WalkSpeed=16 end})
F:CreateSlider({Name="Jump Power",Range={0,1000},Increment=1,CurrentValue=50,Tooltip="Изменяет силу прыжка",Callback=function(a) c.Character.Humanoid.JumpPower=a end})
F:CreateButton({Name="Reset Jump Power",Callback=function() c.Character.Humanoid.JumpPower=50 end})
F:CreateToggle({Name="Infinite Jumps",CurrentValue=false,Tooltip="Позволяет прыгать бесконечно",Callback=function(a) f=a if a then e.JumpRequest:Connect(function() if f then c.Character.Humanoid:ChangeState("Jumping") end end) end end})
F:CreateSection("Environment")
F:CreateSlider({Name="Gravity",Range={0,1000},Increment=1,CurrentValue=196,Tooltip="Меняет силу гравитации",Callback=function(a) workspace.Gravity=a end})
F:CreateButton({Name="Reset Gravity",Callback=function() workspace.Gravity=196 end})
F:CreateSlider({Name="Field of View",Range={1,120},Increment=1,CurrentValue=70,Tooltip="Меняет FOV камеры",Callback=function(a) workspace.CurrentCamera.FieldOfView=a end})
F:CreateButton({Name="Reset FOV",Callback=function() workspace.CurrentCamera.FieldOfView=70 end})
local function J(a)d[a]:FireServer(1)end
G:CreateSection("Default Lucky Block 🟩")
G:CreateButton({Name="Spawn",Callback=function() J("SpawnLuckyBlock") end})
G:CreateToggle({Name="Auto Spawn",CurrentValue=false,Callback=function(a) f=a; while f do task.wait(0.1) J("SpawnLuckyBlock") end end})
G:CreateSection("Super Lucky Block 🟦")
G:CreateButton({Name="Spawn",Callback=function() J("SpawnSuperBlock") end})
G:CreateToggle({Name="Auto Spawn",CurrentValue=false,Callback=function(a) f=a; while f do task.wait(0.1) J("SpawnSuperBlock") end end})
G:CreateSection("Diamond Lucky Block 💎")
G:CreateButton({Name="Spawn",Callback=function() J("SpawnDiamondBlock") end})
G:CreateToggle({Name="Auto Spawn",CurrentValue=false,Callback=function(a) f=a; while f do task.wait(0.1) J("SpawnDiamondBlock") end end})
G:CreateSection("Rainbow Lucky Block 🌈")
G:CreateButton({Name="Spawn",Callback=function() J("SpawnRainbowBlock") end})
G:CreateToggle({Name="Auto Spawn",CurrentValue=false,Callback=function(a) f=a; while f do task.wait(0.1) J("SpawnRainbowBlock") end end})
G:CreateSection("Galaxy Lucky Block 🌌")
G:CreateButton({Name="Spawn",Callback=function() J("SpawnGalaxyBlock") end})
G:CreateToggle({Name="Auto Spawn",CurrentValue=false,Callback=function(a) f=a; while f do task.wait(0.1) J("SpawnGalaxyBlock") end end})
H:CreateButton({Name="Night",Callback=function() game.Lighting.ClockTime=0 end})
H:CreateButton({Name="Day",Callback=function() game.Lighting.ClockTime=12 end})
H:CreateButton({Name="Evening",Callback=function() game.Lighting.ClockTime=18 end})
H:CreateButton({Name="Morning",Callback=function() game.Lighting.ClockTime=6 end})
I:CreateSection("Weapons")
I:CreateButton({Name="Equip All Tools",Callback=function() for a,b in pairs(c.Backpack:GetChildren())do b.Parent=c.Character task.wait() end end})
I:CreateButton({Name="Insane Damage (Best Swords)",Callback=function() C() end})
I:CreateSection("Combat")
I:CreateButton({Name="Kill All",Callback=function() C() for a,b in pairs(b:GetPlayers())do if b.Character and b.Character:FindFirstChild("Humanoid")then if c.Character.Humanoid.Health>0 and b.Character.Humanoid.Health>0 then if not f or not c:IsFriendsWith(b.UserId)then B(b)end end end end end})
I:CreateToggle({Name="Kill Aura",CurrentValue=false,Callback=function(a) if a then C() g=coroutine.create(function() while a do pcall(function() local a=c.Character and c.Character:FindFirstChild("HumanoidRootPart") if a then for b,d in pairs(b:GetPlayers())do if d~=c and d.Character and d.Character:FindFirstChild("HumanoidRootPart")then if(a.Position-d.Character.HumanoidRootPart.Position).Magnitude<=50 then if d.Character.Humanoid.Health>0 then if not f or not c:IsFriendsWith(d.UserId)then B(d)end end end end end end) task.wait(0.5) end end) coroutine.resume(g) elseif g then coroutine.close(g) g=nil end end})
I:CreateSection("Teleportation")
local K={} for a,b in pairs(b:GetPlayers())do if b~=c then table.insert(K,b.Name)end end
I:CreateDropdown({Name="Teleport to Player",Options=K,Callback=function(a) local b=b:FindFirstChild(a) if b and b.Character and b.Character:FindFirstChild("HumanoidRootPart")then c.Character.HumanoidRootPart.CFrame=b.Character.HumanoidRootPart.CFrame+Vector3.new(0,3,0)end end})
I:CreateButton({Name="Teleport All to Me",Callback=function() for a,b in pairs(b:GetPlayers())do if b~=c and b.Character and b.Character:FindFirstChild("HumanoidRootPart")then b.Character.HumanoidRootPart.CFrame=c.Character.HumanoidRootPart.CFrame+Vector3.new(0,3,0)end end end})
I:CreateSection("Options")
I:CreateToggle({Name="Whitelist Friends",CurrentValue=false,Callback=function(a) f=a end})
